from collections.abc import Callable, Iterable, Sequence
from random import Random
from typing import Any, TYPE_CHECKING

from .compilable import Compilable, CustomCompilable
from .randbytes import RandBytes
from .utils import charset_with_fallback

if TYPE_CHECKING:
    from .automata import CRIMEAutomaton

__all__ = [
    "Gadget",
    "GenericMatch",
    "PrecompiledGadget",
    "RandomGadget",
    "CustomGadget",
    "PlaceholderGadget",
    "NullGadget",
    "CustomOrRandomGadget",
    "ParallelGadget",
    "SeriesGadget",
    "MirrorGadget",
]


class Gadget(Compilable):
    def __init__(self, machine: "CRIMEAutomaton | None" = None):
        self.prev_gadget: Gadget | None = None
        # Not really `Any` but `Self`, just too tired to care about types
        self.actions: list[Callable[[Any], None] | None] = []
        super().__init__(machine=machine)

    def _last_bytes(self, length: int, strict: bool = True) -> bytes:
        """Fetch the last `length` bytes of output from the gadgets preceding
        the current gadget. If `strict=False`, then at most `length`
        bytes are returned.
        """
        assert length >= 0
        if length == 0:
            return b""
        if self.prev_gadget is None:
            assert not strict
            return b""
        prev_output = self.prev_gadget.output
        if prev_output is None:
            assert not strict
            return b""

        prev_len = len(prev_output)
        if prev_len >= length:
            return prev_output[-length:]
        else:
            return self.prev_gadget._last_bytes(length - prev_len, strict) + prev_output

    @staticmethod
    def compound_word(pref_len: int, rest: bytes) -> Callable[["Gadget"], bytes]:
        """Return a closure that on call with an argument `gadget` returns a
        byte string generated by concatenating the last `pref_len` bytes before
        `gadget` in the output of the automaton and a byte string `rest`."""
        return lambda gadget: gadget._last_bytes(pref_len, strict=True) + rest

    def derive_precompiled_gadget(
        self, rng: Random | None = None, force_recompile: bool = False
    ) -> "PrecompiledGadget | None":
        """Derive a precompiled gadget from the current gadget.

        Again, one should be very careful when invoking this method for some
        gadget that on compilation spawns actions which in turn uses some
        attributes or methods of the gadget; the current solution is to rebind
        `self` to the precompiled gadget, which may cause unintended behaviors.
        """
        self.compile(rng=rng, force_recompile=force_recompile, execute_actions=False)
        if self.output is None:  # compilation failed
            return None
        return PrecompiledGadget(self.output, self.actions)

    def sanity_check(self) -> bool:
        """Check whether the parameters for the gadget are reasonable.

        The sanity check should be simple, and in particular should not
        depend on other gadgets or compile anything. We also wish to place the
        checks for parameter choices that make no sense at all in __init__().
        The idea is that the sanity check should stop a normal user from using
        incorrect parameters that affect the correctness of the gadget, but can
        be disabled by advanced users if they want to do some weird stuff."""
        return True

    def set_prev_gadget(self, gadget: "Gadget | None") -> None:
        """Set `prev_gadget` to be `gadget`."""
        self.prev_gadget = gadget


class GenericMatch(Gadget):
    """A good ol' match gadget.

    Probably creates a length difference for most compressors out there, but
    may not be able to be chained with other gadgets for non-LZ compressors."""

    def __init__(self, target: bytes):
        super().__init__()
        self.content: bytes = target

    def __bytes__(self) -> bytes:
        return self.content


class PrecompiledGadget(Gadget):
    """A precompiled gadget.

    The output and actions (if any) of the gadget are provided on creation."""

    def __init__(
        self,
        compiled_output: bytes,
        compiled_actions: list[Callable[[Any], None] | None] | None = None,
    ):
        super().__init__()
        self.compiled_output: bytes = compiled_output
        if not compiled_actions:
            compiled_actions = []
        self.compiled_actions: list[Callable[[Compilable], None] | None] = [
            action for action in compiled_actions if action
        ]

        self.output = compiled_output
        self.actions = compiled_actions

    def __call__(self, rng: Random | None = None) -> bytes:
        self.actions = self.compiled_actions
        return self.compiled_output


class RandomGadget(Gadget):
    """A gadget constructed as a random byte string."""

    def __init__(self, length: int, charset: bytes | None = None):
        super().__init__()
        assert length >= 0
        self.length: int = length
        self.charset: bytes | None = charset

    def __call__(self, rng: Random | None) -> bytes:
        charset = charset_with_fallback(self.charset, self.machine)
        return RandBytes(charset, rng).randbytes(self.length)


class CustomGadget(CustomCompilable, Gadget):
    """This type of gadget only works after some hacks because I don't really
    understand mro in python, so take it with a grain of salt."""

    pass


class PlaceholderGadget(Gadget):
    """A gadget that acts as a placeholder for some other gadgets."""

    def __init__(self, label: str | bytes = b""):
        """Initialize a placeholder gadget.

        Args:
            label: The label of the placeholder; default b"".
        """
        super().__init__()
        if isinstance(label, str):
            label = label.encode()
        self.placeholder_label: bytes = label

    def __bytes__(self) -> bytes:
        return self.placeholder_label

    def sanity_check(self) -> bool:
        return False


class NullGadget(Gadget):
    """An empty gadget."""

    def __bytes__(self) -> bytes:
        return b""


class CustomOrRandomGadget(Gadget):
    """A gadget that can be constructed in two ways, either with its content
    provided on initialization or constructed as a random byte string."""

    def __init__(
        self,
        content: bytes | None = None,
        length: int | None = None,
        charset: bytes | None = None,
    ):
        super().__init__()
        self.content: bytes | None = content
        self.length: int | None = length if content is None else len(content)
        self.charset: bytes | None = charset

    def get_length(self) -> int:
        """Get or compute the length of the gadget. Override this method
        to allow determining the length of the gadget on compile time."""
        return 0 if self.length is None else self.length

    def __call__(self, rng: Random | None) -> bytes | None:
        if self.content is not None:
            return self.content
        charset = charset_with_fallback(self.charset, self.machine)
        return RandBytes(charset, rng).randbytes(self.get_length())


class ParallelGadget(Gadget):
    """A gadget composed of several different gadgets in parallel, which
    resolves to one of the constituent gadgets on compilation.

    A `ParallelGadget` can be used to automatically select on compile time
    which gadget to use among several gadgets with the same functionality but
    designed for different DEFLATE parameters.
    """

    def __init__(
        self,
        gadgets: Sequence[Gadget],
        resolver: Callable[["ParallelGadget"], Gadget | None] | None = None,
    ):
        """Initialize a parallel gadget.

        Args:
            gadgets: A sequence of gadgets; if `resolver` (see below) is not
                provided or is `None`, then the gadgets closer to the front of
                the sequence have higher priorities.
            resolver: An optional custom-defined function that selects one of
                the gadgets to use on compile time. Default `None`.
        """
        assert len(gadgets) > 0
        self.gadgets = gadgets
        self.resolver = resolver
        self.gadget_in_use: Gadget | None = None
        super().__init__()

    def resolve(self) -> Gadget | None:
        if self.resolver is not None:
            return self.resolver(self)
        for gadget in self.gadgets:
            if gadget.sanity_check():
                return gadget
        return None

    def set_prev_gadget(self, gadget: "Gadget | None") -> None:
        super().set_prev_gadget(gadget)
        for sub_gadget in self.gadgets:
            sub_gadget.set_prev_gadget(gadget)

    def bind(self, machine: "CRIMEAutomaton | None", should_flush: bool = True) -> None:
        super().bind(machine, should_flush=should_flush)

        for gadget in self.gadgets:
            gadget.bind(machine=machine, should_flush=True)

    def __call__(self, rng: Random | None) -> bytes | None:
        self.gadget_in_use = cur_gadget = self.resolve()
        if cur_gadget is None:
            return None

        output = cur_gadget.compile(rng, force_recompile=True, execute_actions=False)
        self.actions = cur_gadget.actions
        return output

    def sanity_check(self) -> bool:
        for gadget in self.gadgets:
            if gadget.sanity_check():
                return True
        return False


class SeriesGadget(Gadget):
    """A gadget composed of several gadgets connected in series."""

    def __init__(
        self,
        gadgets: Iterable[Gadget],
    ):
        """Initialize a series gadget.

        Args:
            gadgets: A sequence of gadgets. The constructed `SeriesGadget`
                keeps the order of the gadgets in `gadgets`.
        """
        super().__init__()
        self.gadgets = [gadget for gadget in gadgets]
        assert len(self.gadgets) > 0

    def set_prev_gadget(self, gadget: "Gadget | None") -> None:
        super().set_prev_gadget(gadget)
        self.gadgets[0].set_prev_gadget(gadget)

    def bind(self, machine: "CRIMEAutomaton | None", should_flush: bool = True) -> None:
        super().bind(machine, should_flush=should_flush)

        for gadget in self.gadgets:
            gadget.bind(machine=machine, should_flush=True)

    def __call__(self, rng: Random | None) -> bytes | None:
        """We use a hack in this method to make it portable as a pre-compiled
        gadget. This should work but not quite efficient as you can see."""
        cached_gadgets: list[PrecompiledGadget] = []
        for gadget in self.gadgets:
            pc_gadget = gadget.derive_precompiled_gadget(force_recompile=True)
            if pc_gadget is None:
                return None
            cached_gadgets.append(pc_gadget)

        output = b""

        def align_prev_gadget(gadget: Gadget) -> None:
            cached_gadgets[0].set_prev_gadget(gadget)

        self.actions = [align_prev_gadget]

        for pc_gadget in cached_gadgets:
            output += pc_gadget.compiled_output
            for action in pc_gadget.compiled_actions:
                if action:
                    self.actions.append(lambda _: action(pc_gadget))

        return output

    def sanity_check(self) -> bool:
        for gadget in self.gadgets:
            if not gadget.sanity_check():
                return False
        return True


class MirrorGadget(Gadget):
    """
    A gadget that always produces the same output (and actions) as a previous
    gadget in the automaton, unless it is frozen (not recommended).

    Note that we assume the mirror gadget is in the same automaton as the
    gadget being mirrored and the mirror gadget has a higher index in the
    sequence of gadgets, which allows it to always be compiled after the
    mirrored gadget; otherwise, this gadget may not function correctly.
    """

    def __init__(self, model_gadget: Gadget, ignore_actions: bool = False):
        """Initialize a mirror gadget.

        Args:
            model_gadget: The gadget being mirrored, which is supposed to be
                in the same automaton and precede the current gadget.
            ignore_actions: If set to `True`, the gadget will not copy the
                actions of the mirrored gadget on compilation. Default `False`.
        """
        super().__init__()
        self.model_gadget = model_gadget
        self.ignore_actions = ignore_actions

    def sanity_check(self) -> bool:
        return self.model_gadget.sanity_check()

    def __call__(self, rng: Random | None) -> bytes | None:
        output = self.model_gadget.output
        if not self.ignore_actions:
            self.actions = self.model_gadget.actions
        return output

    def compile(
        self, rng: Random | None, force_recompile: bool, execute_actions: bool
    ) -> bytes | None:
        """We override the `compile` method to always force to recompile."""
        return super().compile(rng, True, execute_actions)
