from random import Random, SystemRandom


class RandBytes:
    """Wrapper for generating random bytes."""

    def __init__(self, charset: bytes, rng: Random | None):
        if rng is None:
            rng = SystemRandom()
        self.rng: Random = rng
        self.charset: bytes = charset

    def randbyte(self) -> int:
        """Generate a random byte using `rng`. Override this method to use
        non-uniform distributions, or do other weird stuff as you like."""
        return self.rng.choice(self.charset)

    def randbyte_with_taboo(self, taboo: int | bytes | list[int] | None) -> int:
        """Generate a random byte using `rng`, conditioned on that the
        generated byte is not or does not occur in `taboo`."""
        if taboo is None:
            return self.randbyte()
        if isinstance(taboo, int):
            taboo = [taboo]
        while True:
            c = self.randbyte()
            if c not in taboo:
                return c

    def randbytes(self, k: int) -> bytes:
        """Generate random bytes of length `k` using `rng`."""
        assert k >= 0
        return bytes(self.randbyte() for _ in range(k))
